import fs from 'fs/promises';
import { createWriteStream } from 'fs';
import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, HeadingLevel, TextRun, Table, TableRow, TableCell, WidthType } from 'docx';
import { extractFindings, severityCounts } from './utils/findings.js';

/**
 * Professional report export — turn a run JSON into a PDF, DOCX, or HTML
 * assessment report with an executive summary, risk matrix, findings table, and
 * a per-step appendix.
 */

const SEV_COLOR = { critical: '#cc0000', high: '#e8590c', medium: '#f08c00', low: '#5c940d', info: '#1971c2' };

/** Reports written by older runner versions may lack the findings rollup. */
function ensureFindings(report) {
  const findings = Array.isArray(report.findings) ? report.findings : extractFindings(report);
  const counts = report.severityCounts || severityCounts(findings);
  return { findings, counts };
}

function meta(report) {
  return {
    title: report?.playbook?.title || report?.playbook?.id || 'Recon Report',
    target: report?.vars?.target || 'unknown',
    started: report?.startedAt || '',
    ended: report?.endedAt || '',
    steps: report?.outputs || [],
  };
}

// ── HTML ─────────────────────────────────────────────────────────────────────
function buildHtml(report, branding = {}) {
  const { title, target, started, ended, steps } = meta(report);
  const { findings, counts } = ensureFindings(report);
  const esc = s => String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));

  const findingRows = findings.length
    ? findings.map(f => `<tr><td><span class="sev" style="background:${SEV_COLOR[f.severity] || '#868e96'}">${f.severity.toUpperCase()}</span></td><td>${esc(f.message)}</td><td><code>${esc(f.uses)}</code></td><td>${esc(f.step)}</td></tr>`).join('')
    : '<tr><td colspan="4">No severity-rated findings.</td></tr>';

  const stepRows = steps.map(s =>
    `<tr><td>${esc(s.name)}</td><td><code>${esc(s.uses)}</code></td><td>${s.ok ? '✅ ok' : '❌ ' + esc(s.error || 'failed')}</td></tr>`).join('');

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${esc(title)} — ${esc(target)}</title>
<style>
  body { font: 15px/1.5 -apple-system, Segoe UI, Roboto, sans-serif; color: #1a1a1a; max-width: 880px; margin: 40px auto; padding: 0 20px; }
  h1 { margin-bottom: 4px; } .muted { color: #666; font-size: 13px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0 28px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e5e5e5; vertical-align: top; }
  th { background: #f6f8fa; font-size: 13px; text-transform: uppercase; letter-spacing: .03em; }
  .sev { color: #fff; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
  .matrix td { text-align: center; font-size: 22px; font-weight: 700; }
  .matrix th { text-align: center; }
  code { background: #f6f8fa; padding: 1px 5px; border-radius: 3px; font-size: 13px; }
  .brand { color: #1971c2; font-weight: 700; }
</style></head><body>
  ${branding.company ? `<div class="brand">${esc(branding.company)}</div>` : ''}
  <h1>${esc(title)}</h1>
  <div class="muted">Target: <strong>${esc(target)}</strong> · ${esc(started)} → ${esc(ended)}</div>

  <h2>Executive Summary</h2>
  <p>${findings.length ? `<strong>${findings.length}</strong> finding(s) identified.` : 'No severity-rated findings were identified.'}</p>
  <table class="matrix"><tr><th>Critical</th><th>High</th><th>Medium</th><th>Low</th><th>Info</th></tr>
  <tr><td style="color:${SEV_COLOR.critical}">${counts.critical}</td><td style="color:${SEV_COLOR.high}">${counts.high}</td><td style="color:${SEV_COLOR.medium}">${counts.medium}</td><td style="color:${SEV_COLOR.low}">${counts.low}</td><td style="color:${SEV_COLOR.info}">${counts.info}</td></tr></table>

  <h2>Findings</h2>
  <table><tr><th>Severity</th><th>Finding</th><th>Check</th><th>Step</th></tr>${findingRows}</table>

  <h2>Steps Run (${steps.length})</h2>
  <table><tr><th>Step</th><th>Executor</th><th>Status</th></tr>${stepRows}</table>

  <p class="muted">Generated by CyberAgentToolSet (CATS). Authorized testing only.</p>
</body></html>`;
}

async function writeHtml(report, out, branding) {
  await fs.writeFile(out, buildHtml(report, branding));
  return out;
}

// ── PDF (pdfkit) ─────────────────────────────────────────────────────────────
function writePdf(report, out, branding = {}) {
  const { title, target, started, ended, steps } = meta(report);
  const { findings, counts } = ensureFindings(report);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const stream = createWriteStream(out);
    doc.pipe(stream);

    if (branding.company) doc.fontSize(11).fillColor('#1971c2').text(branding.company);
    doc.fillColor('#000').fontSize(22).text(title, { continued: false });
    doc.moveDown(0.2).fontSize(10).fillColor('#666')
      .text(`Target: ${target}    ${started} -> ${ended}`);
    doc.moveDown();

    doc.fillColor('#000').fontSize(15).text('Executive Summary');
    doc.moveDown(0.3).fontSize(11)
      .text(findings.length ? `${findings.length} finding(s) identified.` : 'No severity-rated findings were identified.');
    doc.moveDown(0.3).fontSize(11).fillColor('#333')
      .text(`Critical: ${counts.critical}   High: ${counts.high}   Medium: ${counts.medium}   Low: ${counts.low}   Info: ${counts.info}`);
    doc.moveDown();

    doc.fillColor('#000').fontSize(15).text('Findings');
    doc.moveDown(0.3).fontSize(10);
    if (findings.length) {
      for (const f of findings) {
        doc.fillColor(SEV_COLOR[f.severity] || '#000').text(`[${f.severity.toUpperCase()}] `, { continued: true })
          .fillColor('#000').text(`${f.message}  (${f.uses} / ${f.step})`);
      }
    } else {
      doc.fillColor('#666').text('None.');
    }
    doc.moveDown();

    doc.fillColor('#000').fontSize(15).text(`Steps Run (${steps.length})`);
    doc.moveDown(0.3).fontSize(10);
    for (const s of steps) {
      doc.fillColor(s.ok ? '#2b8a3e' : '#c92a2a').text(s.ok ? '[ok]  ' : '[fail] ', { continued: true })
        .fillColor('#000').text(`${s.name}  (${s.uses})${s.ok ? '' : ' — ' + (s.error || '')}`);
    }

    doc.moveDown().fontSize(8).fillColor('#999').text('Generated by CyberAgentToolSet (CATS). Authorized testing only.');
    doc.end();
    stream.on('finish', () => resolve(out));
    stream.on('error', reject);
  });
}

// ── DOCX (docx) ──────────────────────────────────────────────────────────────
async function writeDocx(report, out, branding = {}) {
  const { title, target, started, ended, steps } = meta(report);
  const { findings, counts } = ensureFindings(report);

  const cell = (text) => new TableCell({ children: [new Paragraph(String(text))], width: { size: 20, type: WidthType.PERCENTAGE } });
  const matrix = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: ['Critical', 'High', 'Medium', 'Low', 'Info'].map(cell) }),
      new TableRow({ children: [counts.critical, counts.high, counts.medium, counts.low, counts.info].map(cell) }),
    ],
  });

  const children = [
    ...(branding.company ? [new Paragraph({ children: [new TextRun({ text: branding.company, bold: true, color: '1971c2' })] })] : []),
    new Paragraph({ text: title, heading: HeadingLevel.TITLE }),
    new Paragraph({ children: [new TextRun({ text: `Target: ${target}   ${started} -> ${ended}`, color: '666666' })] }),
    new Paragraph({ text: 'Executive Summary', heading: HeadingLevel.HEADING_1 }),
    new Paragraph(findings.length ? `${findings.length} finding(s) identified.` : 'No severity-rated findings were identified.'),
    matrix,
    new Paragraph({ text: 'Findings', heading: HeadingLevel.HEADING_1 }),
    ...(findings.length
      ? findings.map(f => new Paragraph({ children: [
          new TextRun({ text: `[${f.severity.toUpperCase()}] `, bold: true, color: (SEV_COLOR[f.severity] || '#000').replace('#', '') }),
          new TextRun({ text: `${f.message} (${f.uses} / ${f.step})` }),
        ] }))
      : [new Paragraph('None.')]),
    new Paragraph({ text: `Steps Run (${steps.length})`, heading: HeadingLevel.HEADING_1 }),
    ...steps.map(s => new Paragraph(`${s.ok ? '[ok] ' : '[fail] '}${s.name} (${s.uses})${s.ok ? '' : ' — ' + (s.error || '')}`)),
  ];

  const docx = new Document({ sections: [{ children }] });
  const buffer = await Packer.toBuffer(docx);
  await fs.writeFile(out, buffer);
  return out;
}

/**
 * Generate a report file in the requested format from a run report object.
 */
export async function generateReport(report, { format = 'html', out, branding = {} } = {}) {
  switch (format) {
    case 'html': return writeHtml(report, out, branding);
    case 'pdf':  return writePdf(report, out, branding);
    case 'docx': return writeDocx(report, out, branding);
    default: throw new Error(`Unsupported format "${format}". Use html, pdf, or docx.`);
  }
}

/** Load a run JSON file and generate a report from it. */
export async function generateReportFromFile(runPath, opts) {
  const report = JSON.parse(await fs.readFile(runPath, 'utf8'));
  return generateReport(report, opts);
}
